# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/celeste/Documents/Programming/KitchenSinkGames

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/celeste/Documents/Programming/KitchenSinkGames

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/celeste/Documents/Programming/KitchenSinkGames/CMakeFiles /home/celeste/Documents/Programming/KitchenSinkGames//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/celeste/Documents/Programming/KitchenSinkGames/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/celeste/Documents/Programming/KitchenSinkGames/CMakeFiles /home/celeste/Documents/Programming/KitchenSinkGames//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/celeste/Documents/Programming/KitchenSinkGames/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Architectural

# Build rule for target.
Architectural: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Architectural
.PHONY : Architectural

# fast build rule for target.
Architectural/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/build
.PHONY : Architectural/fast

Components/Process/HangmanProcess.o: Components/Process/HangmanProcess.cpp.o
.PHONY : Components/Process/HangmanProcess.o

# target to build an object file
Components/Process/HangmanProcess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/Components/Process/HangmanProcess.cpp.o
.PHONY : Components/Process/HangmanProcess.cpp.o

Components/Process/HangmanProcess.i: Components/Process/HangmanProcess.cpp.i
.PHONY : Components/Process/HangmanProcess.i

# target to preprocess a source file
Components/Process/HangmanProcess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/Components/Process/HangmanProcess.cpp.i
.PHONY : Components/Process/HangmanProcess.cpp.i

Components/Process/HangmanProcess.s: Components/Process/HangmanProcess.cpp.s
.PHONY : Components/Process/HangmanProcess.s

# target to generate assembly for a file
Components/Process/HangmanProcess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/Components/Process/HangmanProcess.cpp.s
.PHONY : Components/Process/HangmanProcess.cpp.s

Components/Render/HangmanRenderer.o: Components/Render/HangmanRenderer.cpp.o
.PHONY : Components/Render/HangmanRenderer.o

# target to build an object file
Components/Render/HangmanRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/Components/Render/HangmanRenderer.cpp.o
.PHONY : Components/Render/HangmanRenderer.cpp.o

Components/Render/HangmanRenderer.i: Components/Render/HangmanRenderer.cpp.i
.PHONY : Components/Render/HangmanRenderer.i

# target to preprocess a source file
Components/Render/HangmanRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/Components/Render/HangmanRenderer.cpp.i
.PHONY : Components/Render/HangmanRenderer.cpp.i

Components/Render/HangmanRenderer.s: Components/Render/HangmanRenderer.cpp.s
.PHONY : Components/Render/HangmanRenderer.s

# target to generate assembly for a file
Components/Render/HangmanRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/Components/Render/HangmanRenderer.cpp.s
.PHONY : Components/Render/HangmanRenderer.cpp.s

Objects/HangmanObject.o: Objects/HangmanObject.cpp.o
.PHONY : Objects/HangmanObject.o

# target to build an object file
Objects/HangmanObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/Objects/HangmanObject.cpp.o
.PHONY : Objects/HangmanObject.cpp.o

Objects/HangmanObject.i: Objects/HangmanObject.cpp.i
.PHONY : Objects/HangmanObject.i

# target to preprocess a source file
Objects/HangmanObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/Objects/HangmanObject.cpp.i
.PHONY : Objects/HangmanObject.cpp.i

Objects/HangmanObject.s: Objects/HangmanObject.cpp.s
.PHONY : Objects/HangmanObject.s

# target to generate assembly for a file
Objects/HangmanObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/Objects/HangmanObject.cpp.s
.PHONY : Objects/HangmanObject.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Architectural.dir/build.make CMakeFiles/Architectural.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Architectural"
	@echo "... Components/Process/HangmanProcess.o"
	@echo "... Components/Process/HangmanProcess.i"
	@echo "... Components/Process/HangmanProcess.s"
	@echo "... Components/Render/HangmanRenderer.o"
	@echo "... Components/Render/HangmanRenderer.i"
	@echo "... Components/Render/HangmanRenderer.s"
	@echo "... Objects/HangmanObject.o"
	@echo "... Objects/HangmanObject.i"
	@echo "... Objects/HangmanObject.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

